//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPStudio.Tools.ReaderMe.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPStudio.Tools.ReaderMe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   本软件是一款电子书阅读软件，是工作之余开发的小玩意儿。
        ///支持格式：TXT
        ///特色功能：老板键、窗口透明度调整、书签、无边框模式、迷你模式
        ///本软件的初衷是功能至上，因此界面并不美观，力求实用而已。
        ///功能方面也都是一些初级的、最常用的功能，致力于满足基本的阅读需要，同时不断加入一些方便的新特性。
        ///由于使用C#开发，因此体积很小，只不过需要.Net FrameWork 2.0的支持。
        ///纯绿色，除了软件自身的配置文件外，不会向系统内写入任何数据，也不会记录任何系统数据。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日期：2012-08-28
        ///版本：1.1.0.13
        ///更新：
        ///添加 主窗口加入“总在最上“快捷菜单
        ///修改 调整一些界面元素
        ///
        ///日期：2011-12-16
        ///版本：1.1.0.12
        ///更新：
        ///修改 保证使程序窗体显示在屏幕范围内
        ///
        ///日期：2011-07-29
        ///版本：1.1.0.11
        ///更新：
        ///修改 优化代码内部结构
        ///
        ///日期：2011-06-28
        ///版本：1.1.0.10
        ///更新：
        ///修改 文件阅读进度百分比保证小数点后保持两位
        ///修改 修正Ctrl + V粘贴时会将内容粘贴两次的错误
        ///
        ///日期：2011-06-16
        ///版本：1.1.0.9
        ///更新：
        ///修改 文件阅读进度百分比保留小数点后两位
        ///
        ///日期：2011-05-11
        ///版本：1.1.0.8
        ///更新：
        ///修改 修正文件编码设置错误的情况下引起程序卡死的错误
        ///修改 修正&quot;自动换行&quot;选项有时没有效果的错误
        ///修改 修正智能去除空行时,会产生两条阅读历史记录的错误
        ///添加 加入&quot;只读模式&quot;选项,在只读模式下,不能对文件进行编辑
        ///添加 只读模式下,空格键也可以实现翻页功能
        ///
        ///日期：2011-04-19
        ///版本：1.1.0.7
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReleaseHistory {
            get {
                return ResourceManager.GetString("ReleaseHistory", resourceCulture);
            }
        }
    }
}
